services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ssdlc-demo:local
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; import sys; sys.exit(0 if requests.get('http://127.0.0.1:8000/health', timeout=2).ok else 1)"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped 