name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -e .[dev]
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Lint
        run: make lint
      - name: Type check
        run: make type-check
      - name: Security scan (Bandit)
        run: make security-scan
      - name: Tests
        run: make test
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  sonar:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.ref != 'refs/heads/main' || github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install .[dev]
      - name: Run tests to generate coverage
        run: pytest -q
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 

  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov IaC scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra
          quiet: true
          framework: terraform
          download_external_modules: true 